sudo: required

services:
  - docker

env:
  global:
    - VERSION=5.7.3
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=snmpd
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=snmpd
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/snmpd/d6j0yrVl4f8_tXwl9FtB23DEx6o=
    - secure: RaErycmqcaDlQ4OBNB0ycCpHn/qlgtO3C9URmeAC4PYzpZZWhxLsU5x/0ZJsuw3CFA+i3bYbCxbROP+zneCL0MRw+NTqoKCceKQe7xNnF4qB9bPiyZAK+5Mh+/ZgHQ6syF1TTUVrwXfRK0P6xRYhdjs+bAoaNHW8VF+oXwiKGKt6KaMtt1f++U0z8RJI8Il/+bO5bcAhT8+AkftE/mpIurd80+bOrpSz0NMSzyqRUyr5kmbR+hdCYL4ByRVhnZDcKBZyXacD64JHoPuy3JNQJeDBBAZ+yw8wsAjPwhtnVke4DBHjjkEwtrbXzc0gnIR44NQPRl9Zn9XUwXWjXM0RXl5aOdYnd+Gea8In1wH5LCy0u93OJl4gv86z8JmNPsfyMvrz1FBXfVRbBagn3gK69dDIYFYYH0++Y8M/hOc2DiWHNcNSc1Nzc9Bw5DWX3n8iskKwWHJRVycfh6auW7cDE3st+sSIhY2NO/Dg9Q3phr5COBaDBaEh+Ah9fe6ZQ6aF5x8gqX73Q7GwBsQ/4lu8VJLbqtNZIYIoKVFgmnO+R5tb0NBD6NHLvfW8X7aspsd3kbjYRnGb/bvulrvyzsApSPEpFiPcILkqxLbygdKW7qKL3NlvaO+PD9YC0KcgnFND/RYu5IxxcQoEHh+oXaLks+o+NZNwQmnhMjwJ5ZqJvNU= # DOCKER_PASSWORD
    - secure: ikRjOEqwdUJSNFkg1tBy5qJ6nSfLINJuinPepgMyN3QgtYiip5nOzJEM8GA9iw3RavW4gtbqHe8M/qhTEnnXDfGerGYzwReOWP89l/4HSZvOuATmUaCgZ2rfGXoYe/flkX/THajxQNXYeEfIhx/6suX9OgZdOdKL8W+gdGS/BOPAyfJ7gqgoGp33HyGa4zjhnxtqZbBnr2gXzi1ZSwKbT5iCmR1xR2/VC79QcxTrFYxkqsHmLRRVbdcWyYZP7kzGKMrHYvaWN4X/xBebGyhY2M2NoBCY3pU0xBCnysa2oW8T7Ddlto7B8/UHp6pfdzj2hk1t857AOyUoUkklHmtmrrLTIy3IvTKCkhdA/xwq+C8aA3edXroiA3i9WMHX39Xq0TfqMHTgRDpdc7ebA6GsGnsbSTOjNOaB7vWW5IRGP+DAVdY/RViG0SqcuaNbQG1txRkKh/RjFQobJZsRoB3mSEIRJop0jjsjSg38WQvBYrIZWlAcEVu32ZM6t+UCFHnkdYW9R6KAAZok+iJuS9RqQjNKXFMfBEr8UGrk5ERW4sn06K/e3B0rTC6EwGWf33lqjO/xBMn8xAB+uIxY2R80fIIqxw/Pb46zzkU+7FQ9lwIn9nyGdJzOewSlEO+S/gg1J4a05OJDdH1og34Aivk0AbJI0qbgs0XLFzQInk7i3vY= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
